const inputValidateConfig = {
  inputSelector: "input__text-field",
  inputPasswordSelector: "input[type='password']",
  inputErrorSelector: "input__text_error",
  inputHelperTextSelector: "input__helper-text",
  isShowHelperTextSelector: "input__helper-text_show",
  btnSubmitFormSelector: "button",
  isDisableBtnSubmitSelector: "button_disable",
  labelTextSelector: "input__text",
  isValuelabelTextSelector: "input__text_isValue",
}

const chatConfig = {
  messagesSelector: "list-item",
  contentDefaultSelector: "chat__column-default",
  contentDialogSelector: "chat__column-dialog",
  popupAddUserSelector: "popup_add-user",
  popupDeleteUserSelector: "popup_delete-user",
  popupChangeAvatarSelector: "popup_change-avatar",
  isActiveChatSelector: "chat_is-active",
  hiddenChatSelector: "chat__column_is-hidden",
  isActivemobileMenuSelector: "mobile-menu_active",
  isOpenPopupSelector: "popup_opened",
  popoverSelector: "popover",
  btnAttachSelector: "chat-footer__btn-attach",
  isShowPopoverSelector: "popover_is-show",
  menuItemSelector: "menu__item",
  popupContainerSelector: "popup__container",
  editAvatarSelector: "edit-avatar",
  editAvatarTextSelector: "edit-avatar__span",
  menuListElementUserSelector: "menu__list_element_user",
  menuClassSelector: "menu",
  isShowMenuSelector: "menu_is-show",
  menuBtnSelector: "menu__btn",
  searchInputByChatsSelector: "search-chat__input",
  imgFromSearchInputByChatsSelector: "search-chat__img",
}
